version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgis_andalucia
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: streamlit_andalucia
    ports:
     - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
volumes:
  postgis_data: